/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as TextosIndexRouteImport } from './routes/textos.index'
import { Route as TextosSlugRouteImport } from './routes/textos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const TextosIndexRoute = TextosIndexRouteImport.update({
  id: '/textos/',
  path: '/textos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextosSlugRoute = TextosSlugRouteImport.update({
  id: '/textos/$slug',
  path: '/textos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/textos/$slug': typeof TextosSlugRoute
  '/textos/': typeof TextosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/textos/$slug': typeof TextosSlugRoute
  '/textos': typeof TextosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/textos/$slug': typeof TextosSlugRoute
  '/textos/': typeof TextosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contato' | '/textos/$slug' | '/textos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/textos/$slug' | '/textos'
  id: '__root__' | '/' | '/contato' | '/textos/$slug' | '/textos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  TextosSlugRoute: typeof TextosSlugRoute
  TextosIndexRoute: typeof TextosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textos/': {
      id: '/textos/'
      path: '/textos'
      fullPath: '/textos/'
      preLoaderRoute: typeof TextosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textos/$slug': {
      id: '/textos/$slug'
      path: '/textos/$slug'
      fullPath: '/textos/$slug'
      preLoaderRoute: typeof TextosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  TextosSlugRoute: TextosSlugRoute,
  TextosIndexRoute: TextosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
